#!/usr/bin/env python3
"""Make this repo use local sibling checkouts instead of published packages.

External users install the published `emergent-matter-*` packages from the
index. Internal developers keep siblings (sdm-core, sdm-materials, ...)
checked out next to this repo and want their edits to show up immediately,
without ever touching this repo's `pyproject.toml`, `uv.lock`, or `.venv` --
those are the files a plain `git status` and a plain `uv sync` both have to
agree are untouched, in local mode or out of it.

The trick, measured against a local test index with uv 0.12.5: uv has no
supported "use local folders instead" switch (a git-ignored `uv.toml` with
`[tool.uv.sources]` is REJECTED -- uv does not accept `sources` there), so
this builds a second, git-ignored environment, `.venv-local`, from the
lock's own constraints, with local siblings installed editable on top.

Commands:

    em-dev                  make this repo use local siblings (build/refresh
                             .venv-local, and reinstall this repo's own
                             console script from local code when
                             [tool.em-dev] opts in)
    em-dev run <cmd...>      run a command inside .venv-local (--no-sync,
                             never re-syncs it)
    em-dev off               back to published: removes .venv-local (and,
                             in tool mode, reinstalls the pinned published
                             version of the console script)
    em-dev status            local vs published per package, and whether
                             local mode has silently reverted
    em-dev --only a,b        make only these packages local

Stdlib only. Runs on Python 3.9+ (what macOS ships as `python3`) -- this is
why it carries its own minimal TOML reader instead of `tomllib` (3.11+
only), and why it is invoked directly (`python3 scripts/em-dev.py ...`),
never through `uv run`: the whole point is to work before anything is
synced. In a repo with no `emergent-matter-*` dependencies it says "nothing
here to make local" and exits 0.

Distributed by `EmergentMatter/actions`: see templates/manifest.toml. Do
not add third-party imports here -- see the module docstring rule this
repo runs on py313 with, in ../STYLE.md, "no bare pip".
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import socket
import subprocess
import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any

__all__ = [
    "EmDevError",
    "normalize_name",
    "toml_loads",
    "toml_load",
    "own_project_name",
    "own_project_version",
    "is_real_package",
    "dependency_group_names",
    "em_dev_tool_config",
    "platform_extras",
    "lock_packages",
    "discover_ours",
    "SiblingResolution",
    "resolve_root",
    "resolve_sibling",
    "resolve_siblings",
    "filter_only",
    "lock_hash",
    "state_path",
    "read_state",
    "write_state",
    "needs_rebuild",
    "is_editable_direct_url",
    "find_dist_info",
    "site_packages_dir",
]

# The prefix that makes a lock entry "ours". A fixed, org-specific constant,
# not configurable -- this script ships from EmergentMatter/actions and only
# ever runs inside EmergentMatter repos.
OURS_PREFIX = "emergent-matter-"

TOOL_PORT = 47615  # the 127.0.0.1 port a tool repo's local server listens on
VENV_LOCAL = ".venv-local"
CONFIG_FILE = ".em-dev.toml"
STATE_FILE = "em-dev-state.json"
LOCAL_GITIGNORE_LINES = (VENV_LOCAL + "/", CONFIG_FILE)


class EmDevError(RuntimeError):
    """Anything that should stop em-dev with a readable message."""


# ============================================================================
# A minimal, stdlib-only TOML reader.
#
# Python's own `tomllib` needs 3.11+; this script's floor is 3.9 (see module
# docstring), so it cannot be used, and there is no stdlib TOML backport to
# fall back to on 3.9/3.10. Rather than carry two code paths (tomllib when
# available, this reader when not) that could quietly drift apart, this
# reader is used unconditionally, on every Python version -- one behavior to
# test and reason about.
#
# It is a subset of TOML v1.0: tables, array-of-tables, dotted keys, inline
# tables, arrays (incl. multi-line), basic/literal strings (incl. triple-
# quoted), integers, floats, booleans. Both files it ever reads are
# generated by uv (`uv.lock`) or hand-written to a small vocabulary
# (`pyproject.toml`'s `[project]`, `[tool.uv]`, `[tool.em-dev]`,
# `[dependency-groups]`): dates/times are accepted syntactically and
# returned as raw strings, since nothing here ever needs their value.
# ============================================================================


class TomlError(EmDevError):
    """The bundled TOML reader could not parse a file."""


_BARE_KEY_CHARS = frozenset("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-")
_NUMBER_STOP_CHARS = frozenset(",]}\r\n#") | frozenset(" \t")
_ESCAPES = {'"': '"', "\\": "\\", "n": "\n", "t": "\t", "r": "\r", "b": "\b", "f": "\f"}


class _TomlParser:
    """One-shot recursive-descent parser over a full TOML document string."""

    def __init__(self, text: str) -> None:
        self.s = text
        self.i = 0
        self.n = len(text)
        self.root: dict = {}
        self.current: dict = self.root

    def parse(self) -> dict:
        while True:
            self._skip_ws(newlines=True)
            if self.i >= self.n:
                break
            if self.s[self.i] == "[":
                self._parse_table_header()
            else:
                self._parse_keyval_line()
        return self.root

    # -------------------------------------------------------------- lexing

    def _skip_ws(self, *, newlines: bool) -> None:
        while self.i < self.n:
            c = self.s[self.i]
            if c in " \t" or (newlines and c in "\r\n"):
                self.i += 1
            elif c == "#":
                while self.i < self.n and self.s[self.i] not in "\r\n":
                    self.i += 1
            else:
                break

    def _skip_inline_ws(self) -> None:
        while self.i < self.n and self.s[self.i] in " \t":
            self.i += 1

    def _skip_to_eol(self) -> None:
        self._skip_inline_ws()
        while self.i < self.n and self.s[self.i] not in "\r\n":
            self.i += 1

    def _expect(self, ch: str) -> None:
        if self.i >= self.n or self.s[self.i] != ch:
            got = self.s[self.i] if self.i < self.n else "<eof>"
            raise TomlError(f"expected {ch!r} at position {self.i}, got {got!r}")
        self.i += 1

    # --------------------------------------------------------------- keys

    def _parse_key(self) -> str:
        self._skip_inline_ws()
        if self.i < self.n and self.s[self.i] in "\"'":
            return self._parse_string()
        start = self.i
        while self.i < self.n and self.s[self.i] in _BARE_KEY_CHARS:
            self.i += 1
        if start == self.i:
            raise TomlError(f"expected a key at position {self.i}")
        return self.s[start : self.i]

    def _parse_key_path(self) -> list[str]:
        keys = [self._parse_key()]
        self._skip_inline_ws()
        while self.i < self.n and self.s[self.i] == ".":
            self.i += 1
            keys.append(self._parse_key())
            self._skip_inline_ws()
        return keys

    # ------------------------------------------------------------- tables

    def _navigate(self, path: list[str], *, array_table: bool) -> dict:
        d = self.root
        for idx, key in enumerate(path):
            last = idx == len(path) - 1
            if last and array_table:
                lst = d.setdefault(key, [])
                if not isinstance(lst, list):
                    raise TomlError(f"{key!r} is already defined as a non-array table")
                new_tbl: dict = {}
                lst.append(new_tbl)
                return new_tbl
            existing = d.get(key)
            if existing is None:
                existing = {}
                d[key] = existing
            elif isinstance(existing, list):
                existing = existing[-1]  # descend into the most recent array-of-tables entry
            elif not isinstance(existing, dict):
                raise TomlError(f"{key!r} is already defined as a non-table value")
            d = existing
        return d

    def _parse_table_header(self) -> None:
        self._expect("[")
        is_array = False
        if self.i < self.n and self.s[self.i] == "[":
            is_array = True
            self.i += 1
        path = self._parse_key_path()
        self._expect("]")
        if is_array:
            self._expect("]")
        self.current = self._navigate(path, array_table=is_array)
        self._skip_to_eol()

    def _parse_keyval_line(self) -> None:
        path = self._parse_key_path()
        self._skip_inline_ws()
        self._expect("=")
        self._skip_inline_ws()
        value = self._parse_value()
        d = self.current
        for key in path[:-1]:
            nxt = d.get(key)
            if nxt is None:
                nxt = {}
                d[key] = nxt
            d = nxt
        d[path[-1]] = value
        self._skip_to_eol()

    # ------------------------------------------------------------- values

    def _parse_value(self) -> Any:  # returns one of several TOML value types
        self._skip_inline_ws()
        if self.i >= self.n:
            raise TomlError("expected a value, got end of input")
        c = self.s[self.i]
        if c in "\"'":
            return self._parse_string()
        if c == "[":
            return self._parse_array()
        if c == "{":
            return self._parse_inline_table()
        if self.s.startswith("true", self.i) and not self._is_bare_char_at(self.i + 4):
            self.i += 4
            return True
        if self.s.startswith("false", self.i) and not self._is_bare_char_at(self.i + 5):
            self.i += 5
            return False
        return self._parse_number_or_other()

    def _is_bare_char_at(self, pos: int) -> bool:
        return pos < self.n and self.s[pos] in _BARE_KEY_CHARS

    def _parse_string(self) -> str:
        quote = self.s[self.i]
        triple = self.s[self.i : self.i + 3] == quote * 3
        self.i += 3 if triple else 1
        literal = quote == "'"
        if triple and self.i < self.n and self.s[self.i] == "\n":
            self.i += 1  # a newline right after the opening delimiter is trimmed
        closing = quote * 3 if triple else quote
        out: list[str] = []
        while True:
            if self.s.startswith(closing, self.i):
                self.i += len(closing)
                return "".join(out)
            if self.i >= self.n:
                raise TomlError("unterminated string")
            ch = self.s[self.i]
            if not literal and ch == "\\":
                self.i += 1
                if self.i >= self.n:
                    raise TomlError("unterminated escape sequence")
                esc = self.s[self.i]
                if triple and esc in "\r\n":
                    self.i += 1
                    while self.i < self.n and self.s[self.i] in " \t\r\n":
                        self.i += 1
                    continue
                if esc in _ESCAPES:
                    out.append(_ESCAPES[esc])
                    self.i += 1
                elif esc == "u":
                    out.append(chr(int(self.s[self.i + 1 : self.i + 5], 16)))
                    self.i += 5
                elif esc == "U":
                    out.append(chr(int(self.s[self.i + 1 : self.i + 9], 16)))
                    self.i += 9
                else:
                    out.append(esc)
                    self.i += 1
            else:
                out.append(ch)
                self.i += 1

    def _parse_array(self) -> list:
        self._expect("[")
        items: list = []
        while True:
            self._skip_ws(newlines=True)
            if self.i < self.n and self.s[self.i] == "]":
                self.i += 1
                return items
            items.append(self._parse_value())
            self._skip_ws(newlines=True)
            if self.i < self.n and self.s[self.i] == ",":
                self.i += 1
                continue
            self._skip_ws(newlines=True)
            self._expect("]")
            return items

    def _parse_inline_table(self) -> dict:
        self._expect("{")
        d: dict = {}
        self._skip_inline_ws()
        if self.i < self.n and self.s[self.i] == "}":
            self.i += 1
            return d
        while True:
            self._skip_inline_ws()
            path = self._parse_key_path()
            self._skip_inline_ws()
            self._expect("=")
            self._skip_inline_ws()
            v = self._parse_value()
            cur = d
            for key in path[:-1]:
                cur = cur.setdefault(key, {})
            cur[path[-1]] = v
            self._skip_inline_ws()
            if self.i < self.n and self.s[self.i] == ",":
                self.i += 1
                continue
            self._skip_inline_ws()
            self._expect("}")
            return d

    def _parse_number_or_other(self) -> Any:
        start = self.i
        while self.i < self.n and self.s[self.i] not in _NUMBER_STOP_CHARS:
            self.i += 1
        tok = self.s[start : self.i]
        low = tok.lower()
        if low in ("inf", "+inf"):
            return float("inf")
        if low == "-inf":
            return float("-inf")
        if low in ("nan", "+nan", "-nan"):
            return float("nan")
        cleaned = tok.replace("_", "")
        if re.fullmatch(r"[+-]?\d+", cleaned):
            return int(cleaned)
        for prefix, base in (("0x", 16), ("0o", 8), ("0b", 2)):
            if cleaned.lower().startswith(prefix):
                return int(cleaned, base)
        try:
            return float(cleaned)
        except ValueError:
            # A date/time literal, or something unrecognized. Nothing this
            # script reads ever needs the parsed value of one -- returning
            # the raw token keeps the rest of the document parseable.
            return tok


def toml_loads(text: str) -> dict:
    """Parse a TOML document (the subset described in the module docstring)."""
    return _TomlParser(text).parse()


def toml_load(path: Path) -> dict:
    """Parse a TOML file, raising `EmDevError` with the path on failure."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise EmDevError(f"could not read {path}: {exc}") from None
    try:
        return toml_loads(text)
    except TomlError as exc:
        raise EmDevError(f"could not parse {path}: {exc}") from None


# ============================================================================
# Naming and lock parsing
# ============================================================================


def normalize_name(name: str) -> str:
    """PEP 503 normalization: lowercase, runs of `-_.` collapse to one `-`.

    `uv.lock` and a project's own `[project].name` may spell the same
    package with dashes or underscores; every name comparison in this
    script goes through this first so the two always compare equal.
    """
    return re.sub(r"[-_.]+", "-", name).lower()


def own_project_name(pyproject: dict) -> str:
    """The consuming repo's own package/project name, normalized."""
    name = pyproject.get("project", {}).get("name")
    if not name:
        raise EmDevError("pyproject.toml has no [project] name")
    return normalize_name(name)


def own_project_version(pyproject: dict) -> str:
    version = pyproject.get("project", {}).get("version")
    if not version:
        raise EmDevError("pyproject.toml has no [project] version")
    return str(version)


def is_real_package(pyproject: dict) -> bool:
    """False for a `[tool.uv] package = false` project (e.g. a UI-only app): it
    has no importable code of its own, so `-e .` must never be attempted --
    see the module docstring on the `.venv-local/lib/**/toy_ui-*` phantom
    package this omission was measured to produce otherwise."""
    return bool(pyproject.get("tool", {}).get("uv", {}).get("package", True))


def dependency_group_names(pyproject: dict) -> set[str]:
    """The `[dependency-groups]` table's own keys (not their contents)."""
    return set(pyproject.get("dependency-groups", {}).keys())


def em_dev_tool_config(pyproject: dict) -> dict | None:
    """The `[tool.em-dev]` table, or None if this repo hasn't opted into
    tool mode (the table a tool repo adds to its pyproject.toml)."""
    tool = pyproject.get("tool", {}).get("em-dev")
    return tool if isinstance(tool, dict) and tool.get("tool") else None


def platform_extras(tool_em_dev: dict, *, platform: str | None = None) -> list[str]:
    """The extras this platform needs, from `tool-extras = { win32 = [...] }`.
    Mirrors the branch a tool repo's CI os-matrix job takes:
    keyed on `sys.platform`, empty list (no extras) when unlisted."""
    plat = platform if platform is not None else sys.platform
    extras = tool_em_dev.get("tool-extras", {})
    return list(extras.get(plat, []))


def lock_packages(lock: dict) -> list[dict]:
    """The `[[package]]` entries of a parsed `uv.lock`."""
    return list(lock.get("package", []))


def discover_ours(lock: dict, own_name: str) -> list[str]:
    """Every `emergent-matter-*` package name in the lock, transitive
    included (materials arrives only via sdm-core, for example, and this
    reads the whole lock, not just direct dependencies), excluding this
    repo's own package. Sorted for stable, testable output."""
    names = set()
    for pkg in lock_packages(lock):
        name = pkg.get("name")
        if not name:
            continue
        norm = normalize_name(name)
        if norm.startswith(OURS_PREFIX) and norm != own_name:
            names.add(norm)
    return sorted(names)


def locked_version(lock: dict, name: str) -> str | None:
    """The version `uv.lock` records for `name` (normalized), or None."""
    norm = normalize_name(name)
    for pkg in lock_packages(lock):
        pkg_name = pkg.get("name")
        if pkg_name and normalize_name(pkg_name) == norm:
            version = pkg.get("version")
            return str(version) if version is not None else None
    return None


# ============================================================================
# Config and folder resolution
# ============================================================================


class SiblingResolution:
    """Where one `ours` package resolves to, and whether it's usable.

    status is one of:
        "local"          folder exists and its own pyproject.toml declares
                          this exact package name -- safe to install editable
        "missing"        no folder at the resolved path -- published version
                          used
        "name-mismatch"  a folder exists there, but declares a different
                          package name -- published version used, so a
                          same-named-but-wrong sibling folder can never be
                          installed under someone else's name
    """

    __slots__ = ("name", "folder", "status", "found_name")

    def __init__(self, name: str, folder: Path, status: str, found_name: str | None = None):
        self.name = name
        self.folder = folder
        self.status = status
        self.found_name = found_name

    def __repr__(self) -> str:  # pragma: no cover -- debugging aid only
        return f"SiblingResolution({self.name!r}, {self.folder!r}, {self.status!r})"


def load_config(repo: Path) -> dict:
    """The optional `.em-dev.toml`, or {} if absent. Deliberately never
    required to be gitignored via a tracked `.gitignore` edit -- see
    `ensure_local_gitignore`, which keeps it (and `.venv-local/`) out of
    `git status` through the repo's untracked `.git/info/exclude` instead."""
    path = repo / CONFIG_FILE
    if not path.is_file():
        return {}
    return toml_load(path)


def resolve_root(repo: Path, config: dict, env: Mapping[str, str] | None = None) -> Path:
    """Where sibling folders are looked for. `EM_DEV_ROOT` wins over
    `.em-dev.toml`'s `root`, which wins over the default: next to this
    repo. Per the plan's decision, this is never confirmed -- only always
    printed (see `resolve_siblings` callers), so a redirect is never
    silent without also being an interruption."""
    active_env = env if env is not None else os.environ
    root_env = active_env.get("EM_DEV_ROOT")
    if root_env:
        return Path(root_env).expanduser().resolve()
    root_cfg = config.get("root")
    if root_cfg:
        return (repo / root_cfg).resolve() if not Path(root_cfg).is_absolute() else Path(root_cfg)
    return repo.parent


def resolve_sibling(name: str, root: Path) -> SiblingResolution:
    """Resolve one `ours` package name to a folder under `root`, checking
    that the folder's own `pyproject.toml` actually declares that name."""
    folder = root / name
    if not folder.is_dir():
        return SiblingResolution(name, folder, "missing")
    pyproject_path = folder / "pyproject.toml"
    if not pyproject_path.is_file():
        return SiblingResolution(name, folder, "missing")
    try:
        data = toml_load(pyproject_path)
        found = normalize_name(data.get("project", {}).get("name", ""))
    except EmDevError:
        return SiblingResolution(name, folder, "missing")
    if found == name:
        return SiblingResolution(name, folder, "local", found)
    return SiblingResolution(name, folder, "name-mismatch", found)


def resolve_siblings(names: list[str], root: Path) -> list[SiblingResolution]:
    return [resolve_sibling(name, root) for name in names]


def filter_only(
    resolutions: list[SiblingResolution], only: list[str] | None
) -> list[SiblingResolution]:
    """Apply `--only a,b`: each token matches a resolution's full normalized
    name, or a `-`-delimited suffix of it (so "core" matches
    "emergent-matter-sdm-core"). Raises on an unknown or ambiguous token --
    silently installing nothing for a typo would be the exact silent no-op
    this org's tooling refuses to produce."""
    if not only:
        return resolutions
    selected: list[SiblingResolution] = []
    for token in only:
        norm = normalize_name(token)
        matches = [r for r in resolutions if r.name == norm or r.name.endswith("-" + norm)]
        if not matches:
            available = ", ".join(r.name for r in resolutions)
            raise EmDevError(f"--only {token!r} matches no package (have: {available})")
        if len(matches) > 1:
            names = ", ".join(m.name for m in matches)
            raise EmDevError(f"--only {token!r} is ambiguous: matches {names}")
        selected.append(matches[0])
    # De-duplicate while keeping first-seen order, in case two tokens
    # resolve to the same package.
    seen = set()
    out = []
    for r in selected:
        if r.name not in seen:
            seen.add(r.name)
            out.append(r)
    return out


# ============================================================================
# .venv-local freshness
# ============================================================================


def lock_hash(lock_path: Path) -> str:
    return hashlib.sha256(lock_path.read_bytes()).hexdigest()


def state_path(venv_dir: Path) -> Path:
    return venv_dir / STATE_FILE


def read_state(venv_dir: Path) -> dict | None:
    path = state_path(venv_dir)
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def write_state(venv_dir: Path, state: dict) -> None:
    state_path(venv_dir).write_text(
        json.dumps(state, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def _sibling_state_rows(locals_used: list[SiblingResolution]) -> list[dict]:
    return [{"name": r.name, "folder": str(r.folder)} for r in locals_used]


def build_state(lock_hash_value: str, locals_used: list[SiblingResolution]) -> dict:
    return {
        "uv_lock_hash": lock_hash_value,
        "siblings": _sibling_state_rows(locals_used),
    }


def needs_rebuild(
    venv_dir: Path, lock_hash_value: str, locals_used: list[SiblingResolution]
) -> bool:
    """True when `.venv-local` is missing, or its recorded state no longer
    matches the current lock hash and sibling list -- see the module
    docstring's "Freshness" note. This is also what makes a stale prior
    build safe to just overwrite: nothing here trusts .venv-local's content
    once its state file disagrees with the world."""
    if not (venv_dir / "pyvenv.cfg").is_file():
        return True
    state = read_state(venv_dir)
    if state is None:
        return True
    if state.get("uv_lock_hash") != lock_hash_value:
        return True
    current = sorted(tuple(sorted(d.items())) for d in _sibling_state_rows(locals_used))
    stored = sorted(tuple(sorted(d.items())) for d in state.get("siblings", []))
    return stored != current


# ============================================================================
# Reading an installed environment (used by both `status` and tool mode)
# ============================================================================


def site_packages_dir(venv_dir: Path) -> Path | None:
    """The venv's site-packages, on whichever OS built it. Returns None if
    the venv doesn't look like it's been created yet."""
    win = venv_dir / "Lib" / "site-packages"
    if win.is_dir():
        return win
    lib = venv_dir / "lib"
    if lib.is_dir():
        for child in sorted(lib.iterdir()):
            candidate = child / "site-packages"
            if candidate.is_dir():
                return candidate
    return None


def find_dist_info(site_packages: Path, dist_name: str) -> Path | None:
    """The `<name>-<version>.dist-info` directory for `dist_name`
    (normalized), or None if it isn't installed there. Distribution
    directories on disk use underscores where the name has `-`/`.`/`_`, so
    this matches by normalizing each candidate rather than by literal glob."""
    if not site_packages.is_dir():
        return None
    norm = normalize_name(dist_name)
    for child in site_packages.iterdir():
        if not child.name.endswith(".dist-info"):
            continue
        candidate = re.sub(r"-[^-]+\.dist-info$", "", child.name)
        if normalize_name(candidate) == norm:
            return child
    return None


def installed_names(site_packages: Path) -> set[str]:
    """Every normalized distribution name with a `.dist-info` in
    `site_packages`."""
    if not site_packages.is_dir():
        return set()
    names = set()
    for child in site_packages.iterdir():
        if child.name.endswith(".dist-info"):
            names.add(normalize_name(re.sub(r"-[^-]+\.dist-info$", "", child.name)))
    return names


def unlocked_installs(venv_dir: Path, lock: dict, own_name: str) -> list[str]:
    """Anything installed into `venv_dir` that `uv.lock` never pinned at
    all -- a sibling that grew a new, unpinned third-party dependency (see
    the module docstring's "two passes" note). This is deliberately
    independent of whether the two-pass fallback ran: nothing about a
    brand-new, unpinned dependency necessarily conflicts with anything, so
    it can install cleanly in a single pass and still be worth naming.
    """
    site_packages = site_packages_dir(venv_dir)
    if site_packages is None:
        return []
    known = {own_name} | {normalize_name(p["name"]) for p in lock_packages(lock) if p.get("name")}
    return sorted(installed_names(site_packages) - known)


def is_editable_direct_url(dist_info_dir: Path) -> bool | None:
    """Whether a dist-info's `direct_url.json` marks an editable install.
    None if there's no direct_url.json (a normal registry wheel install
    doesn't always carry one) or it can't be read/parsed -- callers treat
    that as "not verifiably editable", never as an error.

    This one function is the entire "reverted local mode" detector: a
    console script (or `.venv-local` package) that em-dev put in editable
    mode reads editable=true here; anything that later reinstalled it from
    the registry (a plain `uv tool upgrade`, for example) reads false, and
    `status` reports the difference. Kept intentionally tiny and
    dependency-free so a tool's own status handler can copy it
    verbatim -- see the module docstring on why it isn't imported instead.
    """
    path = dist_info_dir / "direct_url.json"
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return bool(data.get("dir_info", {}).get("editable", False))


# ============================================================================
# git plumbing: local-only ignore, and sibling status detail
# ============================================================================


def ensure_local_gitignore(repo: Path) -> None:
    """Keep `.venv-local/` and `.em-dev.toml` out of `git status` via the
    repo's own untracked `.git/info/exclude`, never via a tracked
    `.gitignore` edit. `.venv-local/` doesn't strictly need this -- uv
    writes a `.gitignore` containing `*` inside every venv it creates, the
    same way it does for `.venv` -- but `.em-dev.toml` lives at the repo
    root and has nothing else to hide behind. Best-effort: a repo with no
    `.git` directory (a plain checkout, or a test fixture) is left alone.
    """
    git_dir = repo / ".git"
    if not git_dir.is_dir():
        return
    exclude_path = git_dir / "info" / "exclude"
    existing = exclude_path.read_text(encoding="utf-8") if exclude_path.is_file() else ""
    missing = [line for line in LOCAL_GITIGNORE_LINES if line not in existing.splitlines()]
    if not missing:
        return
    exclude_path.parent.mkdir(parents=True, exist_ok=True)
    sep = "" if existing.endswith("\n") or not existing else "\n"
    exclude_path.write_text(existing + sep + "\n".join(missing) + "\n", encoding="utf-8")


def git(args: list[str], cwd: Path) -> tuple[int, str]:
    p = subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True, check=False)
    return p.returncode, p.stdout.strip()


def sibling_git_detail(folder: Path) -> str:
    """A one-line `branch@sha (dirty)` summary for `status`, or "" if the
    folder isn't a git checkout."""
    code, branch = git(["rev-parse", "--abbrev-ref", "HEAD"], folder)
    if code != 0:
        return ""
    code, sha = git(["rev-parse", "--short", "HEAD"], folder)
    sha = sha if code == 0 else "?"
    code, dirty_out = git(["status", "--porcelain"], folder)
    dirty = " (uncommitted changes)" if code == 0 and dirty_out else ""
    return f"{branch}@{sha}{dirty}"


# ============================================================================
# uv subprocess helpers
# ============================================================================


def run_uv(
    args: list[str], *, cwd: Path, env: dict[str, str] | None = None, check: bool = True
) -> subprocess.CompletedProcess:
    """Run `uv <args>`, merged over the current environment plus `env`."""
    full_env = dict(os.environ)
    if env:
        full_env.update(env)
    proc = subprocess.run(
        ["uv", *args], cwd=cwd, env=full_env, capture_output=True, text=True, check=False
    )
    if check and proc.returncode != 0:
        raise EmDevError(
            f"`uv {' '.join(args)}` failed (exit {proc.returncode}):\n{proc.stderr.strip()}"
        )
    return proc


def uv_venv(venv_dir: Path, *, cwd: Path) -> None:
    """Create `.venv-local` if it doesn't already exist. Resolves the
    interpreter the same way `uv sync` would for `.venv` (requires-python,
    `.python-version`, etc.) -- nothing here pins a Python version, so a
    consumer's own floor is respected without duplicating it here."""
    if (venv_dir / "pyvenv.cfg").is_file():
        return
    run_uv(["venv", str(venv_dir)], cwd=cwd)


def export_constraints(repo: Path, out_path: Path, *, skip_names: list[str]) -> None:
    """`uv export --frozen ...`, excluding `skip_names` (the packages about
    to be installed editable) -- see the module docstring's "two passes"
    note. `--frozen` means this never re-resolves or touches `uv.lock`."""
    args = [
        "export",
        "--frozen",
        "--no-hashes",
        "--no-emit-project",
    ]
    for name in skip_names:
        args += ["--no-emit-package", name]
    args += ["-o", str(out_path)]
    run_uv(args, cwd=repo)


def pip_install(
    repo: Path, venv_dir: Path, args: list[str], *, check: bool = True
) -> subprocess.CompletedProcess:
    """`--no-sources` only, deliberately not `--no-config` too: measured
    against a local test index, `--no-config` disables discovering
    `pyproject.toml` outright, which also throws away this repo's own
    `[tool.uv]` index/find-links declaration -- the one thing that lets
    `uv pip install` reach the real published index at all. `--no-sources`
    alone still reads `pyproject.toml`, but ignores only its
    `[tool.uv.sources]` table (path/git/workspace overrides), which is
    exactly and only what must not leak into this install."""
    return run_uv(
        ["pip", "install", "--no-sources", *args],
        cwd=repo,
        env={"VIRTUAL_ENV": str(venv_dir)},
        check=check,
    )


def pip_check(repo: Path, venv_dir: Path) -> str:
    """`uv pip check`'s text output, or "" when it reports nothing wrong."""
    proc = run_uv(["pip", "check"], cwd=repo, env={"VIRTUAL_ENV": str(venv_dir)}, check=False)
    return (proc.stdout + proc.stderr).strip()


# ============================================================================
# The two-pass install
# ============================================================================


def make_local(repo: Path, *, only: list[str] | None = None, quiet: bool = False) -> int:
    """`em-dev`: build or refresh `.venv-local`. Returns an exit code."""

    def out(msg: str = "") -> None:
        if not quiet:
            print(msg)

    lock_path = repo / "uv.lock"
    if not lock_path.is_file():
        raise EmDevError(f"no uv.lock in {repo} -- run `uv lock` first")
    pyproject = toml_load(repo / "pyproject.toml")
    own_name = own_project_name(pyproject)
    lock = toml_load(lock_path)

    ours = discover_ours(lock, own_name)
    if not ours:
        out("nothing here to make local (no emergent-matter-* dependency)")
        return 0

    config = load_config(repo)
    root = resolve_root(repo, config)
    resolutions = resolve_siblings(ours, root)
    resolutions = filter_only(resolutions, only)

    ensure_local_gitignore(repo)

    out(f"sibling root: {root}")
    for r in resolutions:
        if r.status == "local":
            out(f"  {r.name:<40} -> {r.folder}  (local)")
        elif r.status == "missing":
            out(f"  {r.name:<40} -> {r.folder}  (not found -- using published version)")
        else:
            out(
                f"  {r.name:<40} -> {r.folder}  "
                f"(declares {r.found_name!r}, not {r.name!r} -- using published version)"
            )

    locals_used = [r for r in resolutions if r.status == "local"]
    venv_dir = repo / VENV_LOCAL
    current_hash = lock_hash(lock_path)

    if not needs_rebuild(venv_dir, current_hash, locals_used) and only is None:
        out(f"\n{VENV_LOCAL} is already up to date")
        return 0

    if venv_dir.exists():
        shutil.rmtree(venv_dir)
    uv_venv(venv_dir, cwd=repo)

    groups = dependency_group_names(pyproject)
    package = is_real_package(pyproject)
    editable_paths = [str(r.folder) for r in locals_used]
    editable_names = [r.name for r in locals_used]

    constraints_path = venv_dir / "constraints.txt"
    export_constraints(repo, constraints_path, skip_names=editable_names)

    def install_args(*, siblings: list[str]) -> list[str]:
        a = ["-c", str(constraints_path)]
        for path in siblings:
            a += ["-e", path]
        if package:
            a += ["-e", "."]
        if "dev" in groups:
            a += ["--group", "dev"]
        return a

    def warn_unlocked() -> None:
        unlocked = unlocked_installs(venv_dir, lock, own_name)
        if unlocked:
            out(
                "\nwarning: installed with no uv.lock pin at all (a sibling's new "
                f"dependency?): {', '.join(unlocked)}"
            )

    out("\ninstalling into " + str(venv_dir) + " ...")
    proc = pip_install(repo, venv_dir, install_args(siblings=editable_paths), check=False)
    if proc.returncode == 0:
        warn_unlocked()
        write_state(venv_dir, build_state(current_hash, locals_used))
        out("done")
        return 0

    if not editable_paths:
        # No siblings to blame -- a plain install failure, not the
        # out-of-range-sibling case the two-pass fallback exists for.
        raise EmDevError(f"install failed:\n{proc.stderr.strip()}")

    out("\nfull install failed; retrying with siblings installed --no-deps ...")
    out(proc.stderr.strip())

    base_args = ["-c", str(constraints_path)]
    if package:
        base_args += ["-e", "."]
    if "dev" in groups:
        base_args += ["--group", "dev"]
    pip_install(repo, venv_dir, base_args)

    for path in editable_paths:
        pip_install(repo, venv_dir, ["--no-deps", "-e", path])

    check_output = pip_check(repo, venv_dir)
    if check_output:
        out("\nuv pip check:")
        out(check_output)
    warn_unlocked()

    write_state(venv_dir, build_state(current_hash, locals_used))
    out("done (with the warning above)")
    return 0


# ============================================================================
# `em-dev run`
# ============================================================================


def run_in_local(repo: Path, command: list[str]) -> int:
    """`em-dev run <cmd...>`: run inside `.venv-local`, always `--no-sync`
    (a plain `uv run` re-syncs .venv-local back to published versions --
    measured; this is the one path that never does that).

    Uses `UV_PROJECT_ENVIRONMENT`, not `VIRTUAL_ENV` -- measured: `uv run`
    checks that `VIRTUAL_ENV` matches the project's own computed
    environment path (`.venv` by default) and, finding `.venv-local`
    doesn't, WARNS, ignores it, and creates and syncs a real `.venv`
    instead. `UV_PROJECT_ENVIRONMENT` is what actually redirects which
    environment `uv run` treats as the project's own.
    """
    venv_dir = repo / VENV_LOCAL
    if not (venv_dir / "pyvenv.cfg").is_file():
        make_local(repo)
    else:
        pyproject = toml_load(repo / "pyproject.toml")
        lock = toml_load(repo / "uv.lock")
        own_name = own_project_name(pyproject)
        ours = discover_ours(lock, own_name)
        config = load_config(repo)
        root = resolve_root(repo, config)
        locals_used = [r for r in resolve_siblings(ours, root) if r.status == "local"]
        if needs_rebuild(venv_dir, lock_hash(repo / "uv.lock"), locals_used):
            make_local(repo)

    if not command:
        raise EmDevError("em-dev run needs a command, e.g. `em-dev run pytest`")

    env = dict(os.environ)
    env["UV_PROJECT_ENVIRONMENT"] = str(venv_dir)
    bin_dir = venv_dir / ("Scripts" if os.name == "nt" else "bin")
    env["PATH"] = str(bin_dir) + os.pathsep + env.get("PATH", "")
    proc = subprocess.run(["uv", "run", "--no-sync", *command], cwd=repo, env=env, check=False)
    return proc.returncode


# ============================================================================
# `em-dev off`
# ============================================================================


def turn_off(repo: Path, *, quiet: bool = False) -> int:
    def out(msg: str = "") -> None:
        if not quiet:
            print(msg)

    # Checked before anything is touched: refusing after .venv-local is
    # already gone would leave the repo half switched-off (published
    # .venv-local state lost, but the tool still on local code).
    pyproject = toml_load(repo / "pyproject.toml")
    tool_cfg = em_dev_tool_config(pyproject)
    if tool_cfg is not None:
        refuse_if_serve_running()

    venv_dir = repo / VENV_LOCAL
    if venv_dir.exists():
        shutil.rmtree(venv_dir)
        out(f"removed {VENV_LOCAL}")
    else:
        out(f"{VENV_LOCAL} was not present")

    if tool_cfg is not None:
        return tool_off(repo, pyproject, tool_cfg, quiet=quiet)
    return 0


# ============================================================================
# Tool mode (a repo's console script)
# ============================================================================


def tool_server_running(port: int = TOOL_PORT) -> bool:
    """Best-effort check for a tool server already listening on
    127.0.0.1:<port>. Named explicitly in every refusal message, since a
    reinstall while it's running is what leaves a locked, unreplaceable
    executable on Windows."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(0.25)
        try:
            return s.connect_ex(("127.0.0.1", port)) == 0
        except OSError:
            return False


def console_script_name(pyproject: dict) -> str | None:
    scripts = pyproject.get("project", {}).get("scripts", {})
    if not scripts:
        return None
    # A repo opting into tool mode ships exactly one console script; take
    # the first (only) one rather than guessing which of several it means.
    return next(iter(scripts))


def local_checkout_defines_script(folder: Path, script_name: str) -> bool:
    """Whether `folder`'s own pyproject.toml still declares `script_name`
    under `[project.scripts]` -- checked before every tool reinstall, since
    `uv tool install --editable` silently *removes* the tool if it doesn't
    (see the plan's "How it works" step 5)."""
    pyproject_path = folder / "pyproject.toml"
    if not pyproject_path.is_file():
        return False
    data = toml_load(pyproject_path)
    return script_name in data.get("project", {}).get("scripts", {})


def tool_dirs(env: Mapping[str, str] | None = None) -> tuple[Path, Path]:
    """(UV_TOOL_DIR, UV_TOOL_BIN_DIR), resolved the same way `uv tool`
    would: respect the env vars when set (tests isolate them), otherwise
    ask uv directly -- never guess uv's own default location."""
    active_env = env if env is not None else os.environ
    tool_dir = active_env.get("UV_TOOL_DIR")
    bin_dir = active_env.get("UV_TOOL_BIN_DIR")
    if tool_dir and bin_dir:
        return Path(tool_dir), Path(bin_dir)
    proc = subprocess.run(
        ["uv", "tool", "dir"], capture_output=True, text=True, check=False, env=dict(active_env)
    )
    resolved_tool_dir = Path(tool_dir) if tool_dir else Path(proc.stdout.strip())
    proc2 = subprocess.run(
        ["uv", "tool", "dir", "--bin"],
        capture_output=True,
        text=True,
        check=False,
        env=dict(active_env),
    )
    resolved_bin_dir = Path(bin_dir) if bin_dir else Path(proc2.stdout.strip())
    return resolved_tool_dir, resolved_bin_dir


def index_args(pyproject: dict) -> list[str]:
    """`--index <url>` / `--find-links <url>` for every index this
    project's own `pyproject.toml` declares under `[tool.uv]`.

    `uv pip install -e .` run with `cwd=repo` picks this project's index
    config up on its own (measured); `uv tool install` does not -- it
    never reads the target project's `pyproject.toml` at all, editable or
    not, config file or none. Without this, `tool_on`/`tool_off` would
    only resolve `emergent-matter-*` dependencies when the real published
    index happened to also be configured globally (an env var, or a user-
    level uv.toml) rather than in this repo's own pyproject.toml, which is
    where the plan's "one source for environment values" style setup
    actually puts it. Passed explicitly so tool mode doesn't depend on
    that coincidence.
    """
    uv_cfg = pyproject.get("tool", {}).get("uv", {})
    args: list[str] = []
    for entry in uv_cfg.get("index", []):
        url = entry.get("url") if isinstance(entry, dict) else None
        if url:
            args += ["--index", url]
    for url in uv_cfg.get("find-links", []):
        args += ["--find-links", url]
    return args


def refuse_if_serve_running() -> None:
    """Guard shared by every tool reinstall, on or off: `serve` holds its
    own executable open (a locked file on Windows, an in-use binary
    everywhere else), so reinstalling it from under a running process is
    unsafe regardless of which direction the reinstall goes."""
    if tool_server_running():
        raise EmDevError(
            f"refusing to reinstall: something is already listening on "
            f"127.0.0.1:{TOOL_PORT} (a running tool server?) -- stop it first"
        )


def tool_on(repo: Path, pyproject: dict, tool_cfg: dict, *, quiet: bool = False) -> int:
    def out(msg: str = "") -> None:
        if not quiet:
            print(msg)

    refuse_if_serve_running()

    own_name = own_project_name(pyproject)
    script_name = console_script_name(pyproject)
    if script_name is None:
        raise EmDevError("[tool.em-dev] is set but pyproject.toml declares no [project.scripts]")
    if not local_checkout_defines_script(repo, script_name):
        raise EmDevError(
            f"this checkout's pyproject.toml no longer declares the "
            f"{script_name!r} console script -- `uv tool install --editable` "
            "would silently remove the tool instead of updating it"
        )

    lock = toml_load(repo / "uv.lock")
    ours = discover_ours(lock, own_name)
    config = load_config(repo)
    root = resolve_root(repo, config)
    resolutions = resolve_siblings(ours, root)
    out(f"sibling root: {root}")
    for r in resolutions:
        out(f"  {r.name:<40} -> {r.folder}  ({r.status})")
    locals_used = [r for r in resolutions if r.status == "local"]

    extras = platform_extras(tool_cfg)
    target = f".[{','.join(extras)}]" if extras else "."

    args = [
        "tool",
        "install",
        "--no-sources",
        "--force",
        "--editable",
        target,
        *index_args(pyproject),
    ]
    for r in locals_used:
        args += ["--with-editable", str(r.folder)]

    out(f"\nreinstalling the {script_name!r} tool from local code ...")
    run_uv(args, cwd=repo)
    out("done")
    return 0


def tool_off(repo: Path, pyproject: dict, tool_cfg: dict, *, quiet: bool = False) -> int:
    def out(msg: str = "") -> None:
        if not quiet:
            print(msg)

    refuse_if_serve_running()

    own_name = own_project_name(pyproject)
    version = own_project_version(pyproject)
    script_name = console_script_name(pyproject)
    if script_name is None:
        return 0
    out(f"reinstalling {own_name} {version} (published) as the {script_name!r} tool ...")
    # The exact version this repo pins, from pyproject.toml -- never
    # "latest": see the plan's "How it works" step 5. index_args() is why
    # this can find that version at all -- see its docstring.
    run_uv(
        ["tool", "install", "--force", f"{own_name}=={version}", *index_args(pyproject)], cwd=repo
    )
    out("done")
    return 0


def tool_status(repo: Path, pyproject: dict, tool_cfg: dict) -> list[str]:
    """Lines describing whether the console script's tool install is
    currently editable (local) or has reverted to a registry install --
    the "reverted local mode" detector from the plan's step 5/status note.
    """
    script_name = console_script_name(pyproject)
    own_name = own_project_name(pyproject)
    if script_name is None:
        return []
    tool_dir, _bin_dir = tool_dirs()
    # `uv tool install` names the tool environment after the DISTRIBUTION
    # (own_name), not the console script it happens to expose -- measured;
    # the two only look alike here because this org's console scripts are
    # usually named close to their package.
    env_dir = tool_dir / own_name
    site_packages = site_packages_dir(env_dir)
    lines = [f"tool ({script_name}):"]
    if site_packages is None:
        lines.append(f"  not installed as a tool (no {env_dir})")
        return lines
    dist_info = find_dist_info(site_packages, own_name)
    if dist_info is None:
        lines.append(f"  installed, but {own_name} not found in its environment")
        return lines
    editable = is_editable_direct_url(dist_info)
    if editable:
        lines.append("  local (editable)")
    elif editable is False:
        lines.append("  published -- local mode has reverted; run `em-dev` again")
    else:
        lines.append("  published (or unknown -- no direct_url.json)")
    return lines


# ============================================================================
# `em-dev status`
# ============================================================================


def status(repo: Path) -> int:
    pyproject = toml_load(repo / "pyproject.toml")
    lock_path = repo / "uv.lock"
    lock = toml_load(lock_path)
    own_name = own_project_name(pyproject)
    ours = discover_ours(lock, own_name)

    if not ours:
        print("nothing here to make local (no emergent-matter-* dependency)")
        return 0

    config = load_config(repo)
    root = resolve_root(repo, config)
    resolutions = resolve_siblings(ours, root)

    print(f"sibling root: {root}")
    for r in resolutions:
        published = locked_version(lock, r.name)
        if r.status == "local":
            detail = sibling_git_detail(r.folder)
            print(f"  {r.name:<40} local   {r.folder} {detail}".rstrip())
        elif r.status == "missing":
            print(f"  {r.name:<40} published {published}  (no sibling folder at {r.folder})")
        else:
            print(f"  {r.name:<40} published {published}  ({r.folder} declares {r.found_name!r})")

    venv_dir = repo / VENV_LOCAL
    locals_used = [r for r in resolutions if r.status == "local"]
    if not (venv_dir / "pyvenv.cfg").is_file():
        print(f"\n{VENV_LOCAL}: not built -- run `em-dev`")
    elif needs_rebuild(venv_dir, lock_hash(lock_path), locals_used):
        print(f"\n{VENV_LOCAL}: stale -- run `em-dev` to rebuild")
    else:
        print(f"\n{VENV_LOCAL}: up to date")
        check_output = pip_check(repo, venv_dir)
        if check_output:
            print("uv pip check:")
            print(check_output)

    tool_cfg = em_dev_tool_config(pyproject)
    if tool_cfg is not None:
        print()
        for line in tool_status(repo, pyproject, tool_cfg):
            print(line)
    return 0


# ============================================================================
# CLI
# ============================================================================


def _split_only(value: str) -> list[str]:
    return [v.strip() for v in value.split(",") if v.strip()]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="em-dev", description=__doc__.split("\n\n")[0])
    ap.add_argument(
        "--only",
        type=_split_only,
        default=None,
        metavar="a,b",
        help="Make only these packages local",
    )
    sub = ap.add_subparsers(dest="command")
    sub.add_parser("run", add_help=False).add_argument("cmd", nargs=argparse.REMAINDER)
    sub.add_parser("off")
    sub.add_parser("status")

    args, extra = ap.parse_known_args(argv)
    repo = Path.cwd()

    try:
        if args.command == "run":
            command = list(getattr(args, "cmd", []) or extra)
            return run_in_local(repo, command)
        if args.command == "off":
            return turn_off(repo)
        if args.command == "status":
            return status(repo)

        exit_code = make_local(repo, only=args.only)
        if exit_code != 0:
            return exit_code
        pyproject = toml_load(repo / "pyproject.toml")
        tool_cfg = em_dev_tool_config(pyproject)
        if tool_cfg is not None:
            print()
            return tool_on(repo, pyproject, tool_cfg)
        return 0
    except EmDevError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
